# Generated by Django 4.0.4 on 2022-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
                ('number', models.CharField(default='None', max_length=255)),
                ('address', models.CharField(default='None', max_length=255)),
                ('email', models.CharField(default='None', max_length=255)),
                ('username', models.CharField(default='None', max_length=255)),
            ],
        ),
    ]
