# Generated by Django 4.0.4 on 2022-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_user_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
