# Generated by Django 4.0.4 on 2022-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(default='None', max_length=255)),
                ('description', models.CharField(default='None', max_length=255)),
                ('age', models.CharField(default='None', max_length=255)),
                ('q1', models.CharField(default='None', max_length=255)),
                ('q2', models.CharField(default='None', max_length=255)),
                ('q3', models.CharField(default='None', max_length=255)),
                ('q4', models.CharField(default='None', max_length=255)),
                ('q5', models.CharField(default='None', max_length=255)),
                ('q6', models.CharField(default='None', max_length=255)),
                ('q7', models.CharField(default='None', max_length=255)),
                ('q8', models.CharField(default='None', max_length=255)),
                ('username', models.CharField(default='None', max_length=255)),
            ],
        ),
    ]
