# Generated by Django 4.0.4 on 2022-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_delete_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
