# Generated by Django 4.0.4 on 2022-05-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_delete_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='q9',
        ),
    ]
